# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='grid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Grid Label'),
        ),
        migrations.AlterField(
            model_name='datasubmission',
            name='status',
            field=models.CharField(choices=[(b'EXPECTED', b'EXPECTED'), (b'PENDING_PROCESSING', b'PENDING_PROCESSING'), (b'ARRIVED', b'ARRIVED'), (b'VALIDATED', b'VALIDATED'), (b'ARCHIVED', b'ARCHIVED'), (b'PUBLISHED', b'PUBLISHED'), (b'REJECTED', b'REJECTED')], default=b'EXPECTED', max_length=20, verbose_name=b'Status'),
        ),
        migrations.AlterField(
            model_name='datasubmission',
            name='user',
            field=models.CharField(max_length=100, verbose_name=b'User'),
        ),
        migrations.AlterField(
            model_name='variablerequest',
            name='cell_measures',
            field=models.CharField(max_length=200, verbose_name=b'Cell Measures'),
        ),
        migrations.AlterField(
            model_name='variablerequest',
            name='cell_methods',
            field=models.CharField(max_length=200, verbose_name=b'Cell Methods'),
        ),
        migrations.AlterField(
            model_name='variablerequest',
            name='cmor_name',
            field=models.CharField(max_length=20, verbose_name=b'CMOR Name'),
        ),
        migrations.AlterField(
            model_name='variablerequest',
            name='dimensions',
            field=models.CharField(max_length=200, verbose_name=b'Dimensions'),
        ),
        migrations.AlterField(
            model_name='variablerequest',
            name='frequency',
            field=models.CharField(choices=[(b'ann', b'ann'), (b'mon', b'mon'), (b'day', b'day'), (b'6hr', b'6hr'), (b'3hr', b'3hr'), (b'1hr', b'1hr'), (b'subhr', b'subhr'), (b'fx', b'fx')], max_length=200, verbose_name=b'Frequency'),
        ),
        migrations.AlterField(
            model_name='variablerequest',
            name='long_name',
            field=models.CharField(max_length=200, verbose_name=b'Long Name'),
        ),
        migrations.AlterField(
            model_name='variablerequest',
            name='modeling_realm',
            field=models.CharField(max_length=20, verbose_name=b'Modeling Realm'),
        ),
        migrations.AlterField(
            model_name='variablerequest',
            name='positive',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Positive'),
        ),
        migrations.AlterField(
            model_name='variablerequest',
            name='standard_name',
            field=models.CharField(max_length=200, verbose_name=b'Standard Name'),
        ),
        migrations.AlterField(
            model_name='variablerequest',
            name='table_name',
            field=models.CharField(max_length=30, verbose_name=b'Table Name'),
        ),
        migrations.AlterField(
            model_name='variablerequest',
            name='uid',
            field=models.CharField(max_length=200, verbose_name=b'UID'),
        ),
        migrations.AlterField(
            model_name='variablerequest',
            name='units',
            field=models.CharField(max_length=200, verbose_name=b'Units'),
        ),
        migrations.AlterField(
            model_name='variablerequest',
            name='var_name',
            field=models.CharField(max_length=30, verbose_name=b'Var Name'),
        ),
        migrations.AlterField(
            model_name='variablerequest',
            name='variable_type',
            field=models.CharField(choices=[(b'real', b'real'), (b'float', b'float'), (b'None', b'None'), (b'', b'')], max_length=20, verbose_name=b'Variable Type'),
        ),
    ]
