# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0002_auto_20170124_1730'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasubmission',
            unique_together=set([('incoming_directory',)]),
        ),
    ]
