# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0003_auto_20170127_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='climate_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdata_app.ClimateModel', verbose_name=b'Climate Model'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdata_app.Experiment', verbose_name=b'Experiment'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdata_app.Institute', verbose_name=b'Institute'),
        ),
    ]
