# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0004_auto_20170127_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='data_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pdata_app.DataRequest'),
            preserve_default=False,
        ),
    ]
