# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0005_datafile_data_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarequest',
            old_name='end_time',
            new_name='request_end_time',
        ),
        migrations.RenameField(
            model_name='datarequest',
            old_name='start_time',
            new_name='request_start_time',
        ),
    ]
