# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0006_auto_20170207_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name=b'Request Created At')),
                ('date_complete', models.DateTimeField(blank=True, null=True, verbose_name=b'Request Completed At')),
                ('requester', models.CharField(max_length=60, verbose_name=b'Request Creator')),
                ('lotus_job', models.CharField(max_length=20, verbose_name=b'LOTUS Job ID')),
                ('data_request', models.ManyToManyField(to='pdata_app.DataRequest')),
            ],
            options={
                'verbose_name': 'Retrieval Request',
            },
        ),
        migrations.AlterModelOptions(
            name='cedadataset',
            options={'verbose_name': 'CEDA Dataset'},
        ),
        migrations.AlterModelOptions(
            name='climatemodel',
            options={'verbose_name': 'Climate Model'},
        ),
        migrations.AlterModelOptions(
            name='dataissue',
            options={'verbose_name': 'Data Issue'},
        ),
        migrations.AlterModelOptions(
            name='datasubmission',
            options={'verbose_name': 'Data Submission'},
        ),
        migrations.AlterModelOptions(
            name='variablerequest',
            options={'verbose_name': 'Variable Request'},
        ),
        migrations.AlterField(
            model_name='datafile',
            name='directory',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Current directory'),
        ),
    ]
