# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0007_auto_20170208_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Activity ID',
            },
        ),
        migrations.AlterField(
            model_name='datafile',
            name='rip_code',
            field=models.CharField(max_length=20, verbose_name=b'Variant Label'),
        ),
        migrations.AlterField(
            model_name='datarequest',
            name='rip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Variant Label'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='activity_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pdata_app.ActivityId', verbose_name=b'Activity ID'),
            preserve_default=False,
        ),
    ]
