# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0008_auto_20170210_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasubmission',
            name='directory',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Current Directory'),
        ),
    ]
