# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0009_auto_20170216_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrievalrequest',
            name='lotus_job',
        ),
    ]
