# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0012_auto_20170220_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrievalrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Request Creator'),
        ),
    ]
