# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0016_auto_20170224_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='base_output_dir',
            field=models.CharField(default=b'/group_workspaces/jasmin2/primavera4/stream1', max_length=300, verbose_name=b'Base directory for retrieved files'),
        ),
    ]
