# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0017_settings_base_output_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrievalrequest',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Request Deleted At'),
        ),
    ]
