# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0018_retrievalrequest_date_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrievalrequest',
            name='date_complete',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Data Restored At'),
        ),
        migrations.AlterField(
            model_name='retrievalrequest',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Data Deleted At'),
        ),
    ]
