# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0019_auto_20170405_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrievalrequest',
            name='data_finished',
            field=models.BooleanField(default=False, verbose_name=b'Data Finished?'),
        ),
    ]
