# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0020_retrievalrequest_data_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='full_name',
            field=models.CharField(max_length=1000),
        ),
    ]
