# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0021_auto_20170421_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrievalrequest',
            name='end_year',
            field=models.IntegerField(default=2014, verbose_name=b'End Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retrievalrequest',
            name='start_year',
            field=models.IntegerField(default=1950, verbose_name=b'Start Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='base_output_dir',
            field=models.CharField(default=b'/group_workspaces/jasmin2/primavera5/stream1', max_length=300, verbose_name=b'Base directory for retrieved files'),
        ),
    ]
