# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0022_auto_20170913_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrievalrequest',
            name='end_year',
            field=models.IntegerField(null=True, verbose_name=b'End Year'),
        ),
        migrations.AlterField(
            model_name='retrievalrequest',
            name='start_year',
            field=models.IntegerField(null=True, verbose_name=b'Start Year'),
        ),
    ]
