# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0023_auto_20171110_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'File name')),
                ('incoming_directory', models.CharField(max_length=500, verbose_name=b'Incoming directory')),
                ('directory', models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Current directory')),
                ('size', models.BigIntegerField(verbose_name=b'File size')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'File Version')),
                ('frequency', models.CharField(choices=[(b'ann', b'ann'), (b'mon', b'mon'), (b'day', b'day'), (b'6hr', b'6hr'), (b'3hr', b'3hr'), (b'1hr', b'1hr'), (b'subhr', b'subhr'), (b'fx', b'fx')], max_length=20, verbose_name=b'Time frequency')),
                ('rip_code', models.CharField(max_length=20, verbose_name=b'Variant Label')),
                ('grid', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Grid Label')),
                ('start_time', models.FloatField(blank=True, null=True, verbose_name=b'Start time')),
                ('end_time', models.FloatField(blank=True, null=True, verbose_name=b'End time')),
                ('time_units', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Time units')),
                ('calendar', models.CharField(blank=True, choices=[(b'360_day', b'360_day'), (b'365_day', b'365_day'), (b'gregorian', b'gregorian')], max_length=20, null=True, verbose_name=b'Calendar')),
                ('online', models.BooleanField(default=True, verbose_name=b'Is the file online?')),
                ('tape_url', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Tape URL')),
                ('checksum_value', models.CharField(blank=True, max_length=200, null=True)),
                ('checksum_type', models.CharField(blank=True, choices=[(b'SHA256', b'SHA256'), (b'MD5', b'MD5'), (b'ADLER32', b'ADLER32')], max_length=20, null=True)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdata_app.ActivityId', verbose_name=b'Activity ID')),
                ('climate_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdata_app.ClimateModel', verbose_name=b'Climate Model')),
                ('data_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdata_app.DataRequest')),
                ('data_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdata_app.DataSubmission')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdata_app.Experiment', verbose_name=b'Experiment')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdata_app.Institute', verbose_name=b'Institute')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdata_app.Project')),
                ('variable_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdata_app.VariableRequest')),
            ],
            options={
                'verbose_name': 'Replaced File',
            },
        ),
    ]
