# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0025_remove_replacedfile_incoming_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacedfile',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='replacedfile',
            name='online',
        ),
    ]
