# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0026_auto_20171214_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacedfile',
            name='incoming_directory',
            field=models.CharField(default='', max_length=500, verbose_name=b'Incoming directory'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='replacedfile',
            unique_together=set([('name', 'incoming_directory')]),
        ),
    ]
