# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0027_auto_20171214_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='current_stream1_dir',
            field=models.CharField(default=b'/group_workspaces/jasmin2/primavera4/stream1', max_length=300, verbose_name=b'The directory that retrievals are currently being retrieved to.'),
        ),
    ]
