# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0028_settings_current_stream1_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataissue',
            name='issue',
            field=models.CharField(max_length=4000, verbose_name=b'Issue Reported'),
        ),
    ]
