# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0031_auto_20180214_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationdataset',
            name='license',
            field=models.URLField(blank=True, null=True, verbose_name=b'License'),
        ),
    ]
