# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0032_observationdataset_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationdataset',
            name='doi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'DOI'),
        ),
    ]
