# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0034_auto_20180221_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationdataset',
            name='cached_directories',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Directory'),
        ),
        migrations.AddField(
            model_name='observationdataset',
            name='cached_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'End Time'),
        ),
        migrations.AddField(
            model_name='observationdataset',
            name='cached_num_files',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'# Data Files'),
        ),
        migrations.AddField(
            model_name='observationdataset',
            name='cached_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Start Time'),
        ),
        migrations.AddField(
            model_name='observationdataset',
            name='cached_variables',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Variables'),
        ),
    ]
