# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0035_auto_20180221_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationdataset',
            name='cached_variables',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=b'Variables'),
        ),
    ]
