# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0037_auto_20180404_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgfdataset',
            name='drs_id',
        ),
    ]
