# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0041_auto_20190319_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapeChecksum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum_value', models.CharField(max_length=200)),
                ('checksum_type', models.CharField(choices=[(b'SHA256', b'SHA256'), (b'MD5', b'MD5'), (b'ADLER32', b'ADLER32')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='datafile',
            name='tape_size',
            field=models.BigIntegerField(null=True, verbose_name='Size on Tape'),
        ),
        migrations.AddField(
            model_name='tapechecksum',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdata_app.DataFile'),
        ),
    ]
