# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 12:24
from __future__ import unicode_literals

from django.db import migrations


def copy_name(apps, schema_editor):
    """
    Copy DataFile.name to DataFile.incoming_name
    """
    DataFile = apps.get_model('pdata_app', 'DataFile')
    for row in DataFile.objects.all():
        row.incoming_name = row.name
        row.save(update_fields=['incoming_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0043_auto_20190502_1216'),
    ]

    operations = [
        migrations.RunPython(copy_name, reverse_code=migrations.RunPython.noop),
    ]
