# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0043_auto_20190502_1216'),
    ]

    operations = [
    ]
