# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-25 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdata_app', '0045_auto_20190502_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablerequest',
            name='out_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Output Name'),
        ),
    ]
