# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('et_indexer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='original_location',
            field=models.CharField(max_length=500, unique=True, verbose_name='Original Location'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='workspace',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Workspace'),
        ),
    ]
