# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('et_indexer', '0002_auto_20170615_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_value',
            field=models.CharField(max_length=1000),
        ),
    ]
