#!/bin/bash -l
# SYNOPSIS
#
#   run_primavera <python_script.py> <options>
#
# DESCRIPTION
#
#   This script is a thin shell wrapper around Python scripts. All options are
#   passed through to the Python script after some initialisation has been
#   performed.
#
# OPTIONS
#
#   Any additional options or arguments are passed through as-is to the specified
#   processing application.

DMT_DIR=~jseddon/primavera/LIVE-prima-dm
VAL_DIR=~jseddon/primavera/primavera-val

# Remove the following environment variable on LOTUS that breaks conda
unset LSB_ECHKPNT_RSH_CMD

export PATH=/home/users/jseddon/software/miniconda3/bin:$PATH
. activate py3-6_iris2-3_nco
export PYTHON_INTERP=/home/users/jseddon/software/miniconda3/envs/py3-6_iris2-3_nco/bin/python

export DJANGO_SETTINGS_MODULE=pdata_site.settings
export PYTHONPATH=$DMT_DIR:$VAL_DIR:$PYTHONPATH
export PATH=$PATH:/gws/nopw/j04/primavera1/tools/adler32

PYTHON_SCRIPT=$1
shift

"$PYTHON_INTERP" "$DMT_DIR/scripts/$PYTHON_SCRIPT" "$@"

exit_code=$?

# send an email to indicate completion
if [ "$PYTHON_SCRIPT" != "send_emails.py" ] && \
[ "$PYTHON_SCRIPT" != "create_root_chown_list.py" ] && \
[ "$PYTHON_SCRIPT" != "split_retrieve_request.py" ] && \
[ "$PYTHON_SCRIPT" != "auto_validate.py" ]  && \
[ "$PYTHON_SCRIPT" != "utils/esgf_timeseries.py" ]; then
    echo "$PYTHON_SCRIPT complete. Sending email."
    "$PYTHON_INTERP" "$DMT_DIR/scripts/create_email.py" "[PRIMAVERA] $LSB_JOBID finished" "$LSB_JOBNAME has finished"
fi

exit "$exit_code"
